CREATE TABLE T_TRANSLOG_L_D (
   SEQ_NO varchar(32 BYTES) NOT NULL,
   PID varchar(20 BYTES) NOT NULL,
   UID varchar(12 BYTES),
   AAAAA varchar(10 BYTES),
   T_TIME timestamp,
   T52_2 varchar(8 BYTES) NOT NULL,
   T52_4 varchar(32 BYTES),
   T52_5 varchar(32 BYTES),
   T52_6 varchar(128 BYTES),
   T52_7 varchar(2 BYTES),
   T52_8 varchar(32 BYTES),
   T52_9 varchar(4 BYTES),
   T52_10 decimal,
   T52_11 varchar(100 BYTES),
   T52_12 varchar(32 BYTES),
   T52_13 varchar(24 BYTES),
   T52_1 varchar(1 BYTES),
   T52_14 varchar(100 BYTES),
   T52_3 varchar(64) NOT NULL,
   T52_15 varchar(6),
   T52_16 varchar(3),
   CUR_VER_FLAG tinyint DEFAULT '0' NOT NULL,
   CONSTRAINT IDX_PK_T52 PRIMARY KEY (T52_3, SEQ_NO)
);
PARTITION TABLE T_TRANSLOG_L_D ON COLUMN T52_3;
CREATE INDEX IDX_T52_MX ON T_TRANSLOG_L_D (T52_3, T_TIME, T52_2, T52_1);
CREATE INDEX IDX_T52_T_TIME ON T_TRANSLOG_L_D (T_TIME, T52_3, SEQ_NO);



CREATE TABLE T_TRANSLOG_EA (
   PID varchar(20 BYTES) NOT NULL,
   AAAAA varchar(10 BYTES),
   T_TIME timestamp,
   SEQ bigint NOT NULL,
   UID varchar(12 BYTES),
   T50_1 varchar(6 BYTES) NOT NULL,
   T50_2 varchar(4 BYTES) NOT NULL,
   T50_3 timestamp NOT NULL,
   T50_4 varchar(4 BYTES) NOT NULL,
   T50_5 varchar(2 BYTES) NOT NULL,
   T50_6 varchar(128 BYTES) NOT NULL,
   T50_7 varchar(64 BYTES) NOT NULL,
   T50_8 varchar(64 BYTES) NOT NULL,
   CUR_VER_FLAG tinyint DEFAULT '0' NOT NULL,
   CONSTRAINT IDX_PK_T50 PRIMARY KEY (PID, SEQ)
);
PARTITION TABLE T_TRANSLOG_EA ON COLUMN PID;
CREATE INDEX IDX_T50_AAAAA ON T_TRANSLOG_EA (PID, AAAAA);
CREATE INDEX IDX_T50_T_TIME ON T_TRANSLOG_EA (T_TIME);
CREATE INDEX IDX_T50_UID ON T_TRANSLOG_EA (PID, UID);
